# yaml-language-server: $schema=../tools/compose/schemas/cmt-config.schema.json

basePath: .

beforeApplyHooks:
  beforeApplyPrompt:
    command: sh scripts/is-ci.sh

defaults:
  remotePath: /opt/compose
  composeAction: up

hosts:
  - name: arm-srv
    host: arm-srv.shiron.dev
    user: ansible_user
